### ISSUE TITLE
Pinned tabs doesn`t hide when use tree style tab

### ISSUE THREAD

**Issue by Confucij** [seleznev/firefox-extension-htitle#67]
When using  Htitle with tree style tab and autohide tabs pinned tabs doesn`t hide properly - there are gray squares left on their places.
![screenshot from 2015-07-07 10-49-44](https://cloud.githubusercontent.com/assets/941997/8541318/ee0df0b8-2495-11e5-9bc3-7cdca26de78e.png)

**Comment by synapsos** [comment]
TST Autohide does not hide the `.tab-background` which is what you see. This should fix it:
```css
#TabsToolbar[treestyletab-tabbar-autohide="hidden"] .tab-background[pinned],
#TabsToolbar[treestyletab-tabbar-autohide-state="hidden"] .tab-background[pinned] {
  display: none;
}
```
@seleznev I don't know where this would belong...
